const PROFILE_SETTING = {
    REQUEST: 'PROFILE_SETTING_REQUEST',
    SUCCESS: 'PROFILE_SETTING_SUCCESS',
    FAILURE: 'PROFILE_SETTING_FAILURE'
}

const PAYMENT_SETTING = {
    REQUEST: 'PAYMENT_SETTING_REQUEST',
    SUCCESS: 'PAYMENT_SETTING_SUCCESS',
    FAILURE: 'PAYMENT_SETTING_FAILURE'
}

