const SIGNUP={
    // REQUEST: 'SIGUP_REQUEST',
    SUCCESS: 'SIGNUP_SUCCESS',
    // FAILURE: 'SIGNUP_FAILURE'
}

const SIGNIN={
    // REQUEST: 'SIGIN_REQUEST',
    SUCCESS: 'SIGNIN_SUCCESS',
    // FAILURE: 'SIGNIN_FAILURE'
}

const MFA={
    // REQUEST: 'MFA_REQUEST',
    SUCCESS: 'MFA_SUCCESS',
    // FAILURE: 'MFA_FAILURE'
}

const FORGOT_PASSWORD={
    // REQUEST: 'FORGOT_PASSWORD_REQUEST',
    SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    // FAILURE: 'FORGOT_PASSWORD_FAILURE'
}

const NEAREST_SALOON={
    SUCCESS: 'NEAREST_SALOON_SUCCESS'
}

const SELECTED_SALOON_BOOKING = {
    SUCCESS: 'SELCED_SALOON_BOOKING'
}

const SELECTED_STYLIST_BOOKING = {
    SUCCESS: 'SELECTED_STYLIST_BOOKING_SUCCESS'
}

const SELECTED_SERVICE_BOOKING = {
    SUCCESS: 'SELECTED_SERVICE_BOOKING_SUCCESS'
}

const SELECTED_DATE_TIME_BOOKING = {
    SUCCESS: 'SELECTED_DATE_TIME_BOOKING_SUCCESS'
}

const GUEST_USER = {
    SUCCESS: 'GUEST_USER_SUCCESS'
}

const SET_TAB_HEADER = {
    SUCCESS : 'SET_TAB_HEADER_SUCCESS'
}

const SET_USER_DETAIL = {
    SUCCESS: 'SET_USER_DETAIL_SUCCESS'
}

const SET_FAV_SALOON = {
    SUCCESS: 'SET_FAV_SALOON_SUCCESS'
}

const SET_IS_LOGIN = {
    SUCCESS: 'SET_IS_LOGIN_SUCCESS'
}

export {SIGNUP , 
        SIGNIN ,
        MFA ,
        FORGOT_PASSWORD ,
        NEAREST_SALOON ,
        SELECTED_SALOON_BOOKING , 
        SELECTED_STYLIST_BOOKING ,
        SELECTED_SERVICE_BOOKING ,
        SELECTED_DATE_TIME_BOOKING ,
        GUEST_USER ,
        SET_TAB_HEADER,
        SET_USER_DETAIL,
        SET_FAV_SALOON ,
        SET_IS_LOGIN ,
    }

