const SIGNUP={
    REQUEST: 'SIGUP_REQUEST',
    SUCCESS: 'SIGNUP_SUCCESS',
    FAILURE: 'SIGNUP_FAILURE'
}

const SIGNIN={
    REQUEST: 'SIGIN_REQUEST',
    SUCCESS: 'SIGNIN_SUCCESS',
    FAILURE: 'SIGNIN_FAILURE'
}

const MFA={
    REQUEST: 'MFA_REQUEST',
    SUCCESS: 'MFA_SUCCESS',
    FAILURE: 'MFA_FAILURE'
}

const FORGOT_PASSWORD={
    REQUEST: 'FORGOT_PASSWORD_REQUEST',
    SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FAILURE: 'FORGOT_PASSWORD_FAILURE'
}

export {SIGNUP , SIGNIN , MFA , FORGOT_PASSWORD}

